### ISSUE TITLE
How to turn off?

### ISSUE THREAD

**Issue by theJavin** [EightB1ts/uni-sync#1]
Hey, I was wondering how you would suggest to stop running the software if I decided to. I'm enjoying the code so far!

Thanks!

**Comment by EightB1ts** [comment]
What OS are you in? On linux you can run 
systemctl stop uni-sync
and (if you want to disable autostart)
systemctl disable uni-sync 

In windows, go to the %USERPROFILE%\Start Menu\Programs\Startup and remove the executable from the folder. Either restart the machine or manually terminate it in task manager. 

As it stands, there's no GUI interface to close it. I am working on a v2 version of this software that supports all the controllers and provides a simple interface using Tauri. Its still a WIP and wont be complete for another week or two.

**Comment by theJavin** [comment]
I'm on Ubuntu, however I've run both systemctl stop and disable but after restarting the computer still loads the fan profile as normal. The only reason I'm trying to disable in the first place is because even the quiet mode has my fans running at around 1300 rpm for some reason. I have the infinity version of the fans which has fan hub version a102 so that may be the cause.

**Comment by EightB1ts** [comment]
That hub is unlikely to work, I uncovered some varying changes between the hubs while building the FanControl plugin. Have you verified that the process is actually running using the **top** command?

If it's not running, the controllers remember what they've been told, that is unless your PC loses power or it receives a new command. If you unplug your computer from power for 10 seconds the controller will reset to a factory configuration. Otherwise, you'll need to open L-Connect and send a new command to it.

**Comment by theJavin** [comment]
The process was no longer running, however, I had to clear the motherboard cache by clearing the CMOS for the fans to return to normal.

**Comment by kyruzic** [comment]
> What OS are you in? On linux you can run systemctl stop uni-sync and (if you want to disable autostart) systemctl disable uni-sync
> 
> In windows, go to the %USERPROFILE%\Start Menu\Programs\Startup and remove the executable from the folder. Either restart the machine or manually terminate it in task manager.
> 
> As it stands, there's no GUI interface to close it. I am working on a v2 version of this software that supports all the controllers and provides a simple interface using Tauri. Its still a WIP and wont be complete for another week or two.

How is the update coming, would love to help out if you need it.

**Comment by EightB1ts** [comment]
I have pushed an update to Uni-Sync to add additional support. Please test and let me know if it's working with your controller (include controller version)

**Comment by kyruzic** [comment]
Works great now, thanks. I have the a102 on 4 channels and they are all working correctly. Nice work.
