### ISSUE TITLE
Fan curves/ Integrate with liquidctl on linux ?

### ISSUE THREAD

**Issue by CUexter** [EightB1ts/uni-sync#2]
Hi i checked out your plugins for fancontrol. But I want to able to set my curves on linux as well. Is there anyway to do that ?

**Comment by EightB1ts** [comment]
Hi There, sorry for delay. 
This can be compiled for linux, but there's no plugin that supports creating fan curves. Closest current solution would be setting the fan curves in BIOS (if available) and enabling PWM mode using this program.
