### ISSUE TITLE
SL V2-v0.5 (0xa105) doesn't follow motherboard pwm

### ISSUE THREAD

**Issue by expipiplus1** [EightB1ts/uni-sync#4]
Setting a manual speed works fine.

Setting a channel to PWM however just seems to go to some default low speed.

I've tested this with two PWM ports on the motherboard, one fixed-full speed one.

The connector is seated correctly as I can control the LEDs through the motherboard argb header.

**Comment by expipiplus1** [comment]
I can change this setting from a windows VM and sniff the packets,

I do see the data as passed by uni-sync: 

![image](https://github.com/EightB1ts/uni-sync/assets/857308/9d9252e8-148c-4f61-b5ff-a4d4a1cc07e7)


However I guess that there is something else necessary in the other packets.

**Comment by expipiplus1** [comment]
Ah, it seems like the calculation for channel_byte was incorrect, this works.

```
                // Disable Sync to fan header
                let mut channel_byte = 0x10 << x;

                if channels[x].mode == "PWM" {
                    channel_byte = channel_byte | 0x1 << x;
                }
```

**Comment by EightB1ts** [comment]
Much cleaner too, thanks a bunch!

**Comment by expipiplus1** [comment]
Maybe even cleaner would be `(mode == PWM ? 0x11 : 0x10) << x`
