### ISSUE TITLE
uni-sync.service does not exist

### ISSUE THREAD

**Issue by bcarvalho2500** [EightB1ts/uni-sync#8]
Hello when I run the install script and select 'y' to install as a service I get this message.
```
Failed to enable unit: Unit file uni-sync.service does not exist.
Failed to restart uni-sync.service: Unit uni-sync.service not found.
```

**Comment by bcarvalho2500** [comment]
Issued fixed in this PR: https://github.com/EightB1ts/uni-sync/pull/9

**Comment by NoyingNabi** [comment]
Fix did not do it for me, I am using fedora, was using Arch(btw) and it works fine but not on fedora.
